/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

/**
 * SAMPLE AWS EXPORTS - FOR LOCAL DEVELOPMENT ONLY
 * 
 * This is a sample/mock configuration to allow the app to compile without Amplify deployment.
 * 
 * TO USE THIS FILE:
 * 1. Copy this file to src/aws-exports.js:
 *    cp src/aws-exports.sample.js src/aws-exports.js
 * 
 * 2. The app will now compile successfully
 * 
 * TO GENERATE REAL CONFIGURATION:
 * 1. Install Amplify CLI: npm install -g @aws-amplify/cli
 * 2. Configure AWS: aws configure
 * 3. Initialize Amplify: amplify init
 * 4. Deploy backend: amplify push
 * 
 * After running 'amplify push', src/aws-exports.js will be replaced with actual
 * AWS resource configurations (Cognito, AppSync, etc.)
 * 
 * Note: src/aws-exports.js is in .gitignore and should NOT be committed.
 * This sample file (aws-exports.sample.js) IS committed for easy setup.
 */

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_XXXXXXXXX",
  "aws_user_pools_web_client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
  "oauth": {},
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint": "https://XXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "da2-XXXXXXXXXXXXXXXXXXXX"
};

export default awsmobile;
